baseURL = 'https://blog.troubly.fr/'
languageCode = 'en-us'
title = 'Blog.Troubly.fr'
theme = "PaperMod"


[params]
	env = "production"
	author = "Benoit ESTRADE"
	defaultTheme = "auto"
	ShowShareButtons = true
	ShowReadingTime = true
	displayFullLangName = false
	ShowPostNavLinks = true
	ShowBreadCrumbs = true
	ShowCodeCopyButtons = true
	ShowRssButtonInSectionTermList = true
	ShowAllPagesInArchive = true
	ShowPageNums = true
	ShowToc = true
	images = ["images/cover.png"] #Is in /assets/

[params.homeInfoParams]
	Title = "Blog.troubly.fr"
	Content = """
	👋 Welcome to this little blog


	"""

[[params.socialIcons]]
	name = "github"
	title = "Personnal Github profil"
	url = "https://github.com/estradeb"
[[params.socialIcons]]
	name = "LinkedIn"
	title = "My LinkedIn profil"
	url = "https://www.linkedin.com/in/benoit-estrade/"


[menus]
	[[menu.main]]
	identifier = "About"
	name = "About"
	pageRef = "/about/"
	weight = 10

	[[menu.main]]
	name = "Content"
	pageRef = "/posts/"
	weight = 20



[markup.goldmark]
	[markup.goldmark.renderer]
		unsafe= true
#	[markup.goldmark.renderHooks]
#	  [markup.goldmark.renderHooks.image]
#	    enableDefault = true
