baseURL = 'https://blog.troubly.fr/'
languageCode = 'en-us'
title = 'Benoit ESTRADE'
theme = "paper"


[params]
  # color style
  color = 'light'

  # contacts   
  github = 'estradeb'                 # github.com/YOUR_GITHUB_ID
  linkedin = 'benoit-estrade'             # linkedin.com/in/YOUR_LINKEDIN_ID
  rss = true

  # home page profile
  avatar = './data/icons/icon-trotro.png'                 # gravatar email or image url
  name = 'Benoit ESTRADE'


[menus]
	[[menu.main]]
	name = "Home"
	url = "/"
	weight = 1

	[[menu.main]]
	name = "Content"
	weight = 3
	url = "content"
	

[markup]
  defaultMarkdownHandler = 'goldmark'